# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MRS
tagline:          Modelling Reactive Systems
description:      #SHORT COURSE DESCRIPTION
url:              https://gu-cs-notes.github.io/MRS
baseurl:          /MRS				# Note! This should be the repo title preceded by a forward slash, but not followed by one! For example, the baseurl for AI4 is "/AI4"

author:
  name:           'David Creigh'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gu-cs-notes/blackdoc
